version: '3.3'

services:
  db:
    image: postgres
    container_name: docker-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
  server:
    build: ./server
    container_name: docker-backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 192.168.56.10 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=bizone_db
      - SQL_USER=bizone_admin
      - SQL_PASSWORD=bizone_D249GvUT+gHHta@
      - SQL_HOST=db
      - SQL_PORT=5432
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: ./client
    container_name: docker-frontend
    volumes:
      - .:/client
    ports:
      - "8080:8080"
    depends_on:
      - server

volumes:
  postgres_data: